baseURL = 'https://ijborda.github.io/docs-sample'
languageCode = 'en-us'
title = 'AMBDABiDSS-Health Documentation'
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

# Enable dropdowns
[params]
alwaysOpen = true
collapsibleMenu = true